### ISSUE TITLE
Missing wallpapers

### ISSUE THREAD

**Issue by shellwhale** [archcraft-os/archcraft-wallpapers#2]
Where can I find the following wallpapers? https://i.redd.it/v9x0qqhhl6c51.png
I saw these on that Reddit post https://www.reddit.com/r/unixporn/comments/hv4j8u/oc_archcraft_a_minimalistic_linux_distribution/

**Comment by adi1090x** [comment]
All available in here, except the grid one.

**Comment by shellwhale** [comment]
Funny enough I was looking specifically for the grid one.
